// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjdfsueamhqmjiqzrxgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZGZzdWVhbWhxbWppcXpyeGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MTEyOTcsImV4cCI6MjA1Njk4NzI5N30.rfTJLxwkJ7TrzPmzBD89Nhv0TSSkV5ObBvb19eq_kPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);